name: Spring boot sample push to Docker Hub

on:
  push:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Navigate to work dir
      run: |
        ls -ltr .
        cd spring-boot-sample
        ls -ltr .
    - name: Generate artifact
      run: |
        ls -ltr .
        ./gradlew build
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag deepuvsdeepu/spring-boot-sample:latest
      # $(date +%s)
    - name: Docker push
      run: docker push deepuvsdeepu/spring-boot-sample